const msgs = {
  signupSuccess: "Registration Successful: Please Login In",
  failed_signup: "Registration Failed",
  loginSuccess: "Login Successful",
  failed_login: "Login Failed",
  logout: "You're logged out",
  signup: "SignUp for free",
  aboutMsg: "Welcome to the about page",
  bookFound: "Book Found",
  noBookFound: "Could not Find Book",
  booksFound: "Books Found",
  noBooksFound: "No Book Found",
  bookAdded: "The Book has been added to the catalogue",
  editBook: "Here you can edit the information about this book",
  bookUpdated: "Book Updated Successfully",
  bookDeleted: "Book Deleted Successfully",
  noBookAdded: "Could not Add the Book",
  noBookUpdated: "Could not be Update the Book",
  noBookDeleted: "Could not be Delete the Book",
  cantAddAuthor: "Please add a book before adding an author",
  authorFound: "Author Found",
  authorsFound: "Authors Found",
  noAuthorFound: "Could not find the Author",
  noAuthorsFound: "Could not find Authors",
  addAnAuthor: "Here you can add your favourite author",
  authorAdded: "The Author is added to the database",
  editAuthor: "Here you can edit the information about this author",
  authorUpdated: "Author Updated Successfully",
  authorDeleted: "Author Deleted Successfully",
  noAuthorAdded: "Could not Add the Author",
  noAuthorUpdated: "Could not be Update the Author",
  noAuthorDeleted: "Could not be Delete the Author",
  editBookPageFailed: "Could not load editBook Page",
};
export default msgs;
